version: '3.8'
services:
    nest_api:
        # For local build testing
        build: ./
        # For testing build from gh packages
        # image: docker.pkg.github.com/wavilikhin/nest-api/nest-api:develop
        container_name: nest-js-api
        ports:
            - '3000:3000'
        volumes:
            - .env:/opt/app/api/
        depends_on:
            - postgres
        env_file:
            - .env

    postgres:
      image: 'postgres:14.5-alpine'
      container_name: postgres
      restart: always
      ports:
        - 5432:5432
      env_file:
      - .env
      volumes:
        - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db