version: '3.3'
services:
    nest_api:
        # For local build testing
        build: ./
        # For testing build from gh packages
        # image: docker.pkg.github.com/wavilikhin/nest-api/nest-api:develop
        container_name: nest-js-api
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - .env:/opt/app/api/
    postgres:
      image: 'postgres:14.5-alpine'
      ports:
        - 5432:5432
      volumes:
        - ./prisma/:/opt/app/prisma/
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}